M48
; DRILL file {KiCad 7.0.7} date Wed Nov  1 21:34:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-01T21:34:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.0945Y-2.126
X4.0945Y-3.7795
X7.7165Y-2.126
X7.7165Y-3.7795
T0
M30
